spring:
  application:
    name: billing-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/billing_dev
    username: billing_dev
    password: devpass

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

#  security:
#    user:
#      name: devuser
#      password: devpass

server:
  port: 8080
